# Generated by Django 4.2.2 on 2023-08-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_regid_category_catid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=50)),
                ('subcaticonname', models.CharField(max_length=100)),
            ],
        ),
    ]
