# Generated by Django 4.2.2 on 2023-08-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
