# Generated by Django 4.2.2 on 2023-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=50)),
                ('subcatname', models.CharField(max_length=50)),
                ('pdescription', models.CharField(max_length=100)),
                ('pbprice', models.IntegerField()),
                ('piconname', models.CharField(max_length=100)),
                ('info', models.IntegerField()),
            ],
        ),
    ]
